### ISSUE TITLE
Concerns about additional terms of GPL 3.0 for LLC 2.0

### ISSUE THREAD

**Issue by ColorlessColor** [Azukimochi/LightLimitChangerForMA#263]
https://github.com/Azukimochi/LightLimitChangerForMA/blob/924a59e0cdb30c13a7b9c50ac6c9773bb56107da/README.md?plain=1#L33

> 本プロジェクトのReleasesにおける2.x.xバージョンのリリースを含むVPM Listingファイルの作成の禁止

https://mochis-factory.booth.pm/items/4864776

> v2購入にあたっての規約
>
> 原則として以下の条項に合意の上、ご購入をお願いいたします。
>
> ・購入後、ダウンロードできる内容物の公開及び購入者以外への共有の禁止
>
> また、本条項は事前の予告なく変更される可能性があります。
>
>本アセットを活用した写真などの記載を行う際は、クレジット記載などはご自由にお願いいたします。
> ＊ソフト利用前提のものに関しては、本ソフトウェアの仕様・動作が変わる可能性がある旨ご了承お願いします。

Is this compatible with GPL 3.0?

------

BTW, there a typo "GLP" -> "GPL":

https://github.com/Azukimochi/LightLimitChangerForMA/blob/924a59e0cdb30c13a7b9c50ac6c9773bb56107da/README.md?plain=1#L30

**Comment by Azukimochi** [comment]
>本プロジェクトのReleasesにおける2.x.xバージョンのリリースを含むVPM Listingファイルの作成の禁止  

Because there was a problem with this description, it is currently temporarily licensed under the MIT license.

However, since the LLC v2 project is now a private repository, it may not be OSS.

So I am considering whether to create my own license, or keep it as a private repository and keep the software under MIT license.

**Comment by ColorlessColor** [comment]
> However, since the LLC v2 project is now a private repository, it may not be OSS.

What does "private repository" mean, source code or vpm repo?

> ... it is currently temporarily licensed under the MIT license.

The MIT license seems to allow users to create vpm listing and redistribute it.

I am willing to continue paying to use the new features of LLC 2.0. Unfortunately if the project is no longer OSS, I need to reconsider whether to continue to contribute any commits.

**Comment by ColorlessColor** [comment]
Today I noticed on twitter that LLC 2.0 alpha was released then I decided to join the testing and submit l10n text. But since you deleted the v2 branch, unfortunately I can't continue to contribute commits.

Thank you for your hard work in developing LLC :)

**Comment by Azukimochi** [comment]
Regarding the translation, we are currently organizing the repository, so please wait a little longer.

I'm very sorry for the sudden change and the fact that we haven't been able to keep up with the announcements yet.

From now on, we will only upload l10n files to this repository.

And we will also be adding information for contributors to the translation repository, so please wait a little longer.
https://github.com/Azukimochi/LightLimitChangerForMA_v2_Translation

**Comment by Azukimochi** [comment]
> What does "private repository" mean, source code or vpm repo?

Both are now private.
Both the LLC v2 repository and the VPM repository.

> The MIT license seems to allow users to create vpm listing and redistribute it.

This is certainly permitted under MIT. So I am considering creating an original license that does not permit this.
However, since the LLC v2 repository is private now, only collaborators can access it, so I don't think it will be an immediate problem if only purchasers can download it.

**Comment by ColorlessColor** [comment]
Since LLC 2.0 is no longer an OSS project, this issue closed as `not planned`.
